### ISSUE TITLE
No versions available

### ISSUE THREAD

**Issue by 22289d** [DneshP/resize-textarea-vue3#1]
When I try to install this via NPM I get the error message:

No versions available for resize-textarea

Entering: $ npm install resize-textarea

**Comment by DneshP** [comment]
Please try `npm i resize-textarea-vue3`

**Comment by 22289d** [comment]
Thank you for the fast response, it worked! And also the code worked perfectly!

Been trying to solve this problem all day.

**Comment by DneshP** [comment]
@22289d No worries! Good to hear that.
